### ISSUE TITLE
CGAL 5

### ISSUE THREAD

**Issue by oleg-alexandrov** [conda-forge/cgal-feedstock#54]
CGAL 5 was released in November (https://www.cgal.org/2019/11/08/cgal50/). Any chances it would be supported? Thanks.

**Comment by tadeu** [comment]
This feedstock is in need of more maintainers, I'm not being able to dedicate much time to it as of now. `cgal-cpp` is already on `5.0.1`, but we had problems trying to build the bindings since 4.14.2. Would you like to try to contribute a PR for upgrading to CGAL 5.0.1?

**Comment by lrineau** [comment]
@tadeu Can you point to a CI result showing the build issues? The CGAL project might be able to help you with this task.

We already have contributed to package managers (vcpkg, brew), and conda might be our next step.

**Comment by lrineau** [comment]
> @tadeu Can you point to a CI result showing the build issues? The CGAL project might be able to help you with this task.
> 
> We already have contributed to package managers (vcpkg, brew), and conda might be our next step.

Ping @tadeu. I offered to help and I still mean it. The CGAL project has been using `conda` for a few months, for the configuration of our CI environments. That would be fair play from us to help you maintain the CGAL package in conda.

Cc: @maxGimeno... Maxime, I suggest you watch this project https://github.com/conda-forge/cgal-feedstock. The traffic is low, because it is only about the CGAL Python package in conda. See also https://github.com/conda-forge/cgal-cpp-feedstock that is CGAL itself (the header-only C++ library).

**Comment by tadeu** [comment]
Oh, sure @lrineau, sorry if I didn't answer before, I probably missed the notification. There's no PR yet for updating these bindings to version 5, I just didn't took time yet to do this (I was thinking about taking some time this next weekend).

But since you are offering help, I'll try to open the PR now and we'll follow from that!

**Comment by tadeu** [comment]
Done in #57
