### ISSUE TITLE
Update to newer version of cgal-cpp

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/cgal-feedstock#65]
Hi there,
At the moment a really old version of cgal-cpp is pulled in, which itself has a dependency on an old version of boost. The latest cgal-cpp should be pulled in.

Many thanks, Tobi

**Comment by tadeu** [comment]
Hi @Tobias-Fischer !

Unfortunately `regro-cf-autotick-bot` can't update `cgal-feedstock` since there are no official releases for https://github.com/CGAL/cgal-swig-bindings, and this update must be done manually. Do you want to try opening a PR based on the [last update for 5.0.1](https://github.com/conda-forge/cgal-feedstock/pull/57/commits/ddf716480d8f10322758eb6e5155da5d86d09be3#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR1)?

Usually only `version` and `url` must be updated (to get the latest commit), and let's hope that nothing breaks ;)

**Comment by tadeu** [comment]
🎉

**Comment by lrineau** [comment]
> Hi @Tobias-Fischer !
> 
> Unfortunately `regro-cf-autotick-bot` can't update `cgal-feedstock` since there are no official releases for [CGAL/cgal-swig-bindings](https://github.com/CGAL/cgal-swig-bindings), and this update must be done manually. Do you want to try opening a PR based on the [last update for 5.0.1](https://github.com/conda-forge/cgal-feedstock/pull/57/commits/ddf716480d8f10322758eb6e5155da5d86d09be3#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR1)?
> 
> Usually only `version` and `url` must be updated (to get the latest commit), and let's hope that nothing breaks ;)

Dear @Tobias-Fischer, @tadeu,

Things have changed a bit with recent versions of https://github.com/CGAL/cgal-swig-bindings, during summer:
1. Now, the latest version of `cgal-swig-bindings` will only officially support the latest (non-beta) release of CGAL. For example, currently the CI of `cgal-swig-bindings` only tests:
    - CGAL-5.5, as released on https://github.com/CGAL/cgal/releases,
    - the Git branch `5.5.x-branch` from https://github.com/CGAL/cgal, that prepares CGAL-5.5.1,
    - the Git branch `master` from https://github.com/CGAL/cgal, that prepares CGAL-5.6.
2. The CI also pushes Python packages to PyPI: https://pypi.org/project/cgal/. Current latest version is named `5.5.post202210051748`.
3. We have official releases at https://github.com/CGAL/cgal-swig-bindings/releases. See the first release https://github.com/CGAL/cgal-swig-bindings/releases/tag/5.5.post202207291543 for an explanation of the release name.

I hope that can help you provide updated conda packages more easily.
